### ISSUE TITLE
Change Documentation around  available_filters: [],

### ISSUE THREAD

**Issue by deanfields** [jhund/filterrific#110]
Hi, I was following the documentation for implementing this Gem into a rails 5 app, I slimmed it down to just use the sorted_by filter option because I wasn't seeing my results filtered/sorted. 

When changing the select box, the ajax loader appears, and the partial is reloaded into the page but the results just didn't change/ Looking thoroughly through the code it was down to the fact that  available_filters: [] in your examples is empty within the controllers. Removing this now works. 

I think the documentation should be updated to make people aware of this, I don't know if it's isolated around Rails 5?

**Comment by jhund** [comment]
@deanfields thank you for reporting this. I updated the documentation.
