### ISSUE TITLE
Filters not working

### ISSUE THREAD

**Issue by radvc** [jhund/filterrific#134]
I copy the students demo of filterrific to Rails 5.1, but the filters are not working(search, country etc..). I don't know why is this happening, anyone here encounter this issue?

Im using ruby version 2.4 and rails 5.1

**Comment by sanatem** [comment]
I had a problem with the params[:filterrific]
I solved doing this: 

    @filter = initialize_filterrific(
      Promo,
      params[:filterrific].permit!.to_hash,
      select_options: { },
      persistence_id: 'shared_key',
      avalaible_filters:[
        :by_name
      ]
    ) or return
