### ISSUE TITLE
Filterrific listens for changes on every input inside form helper

### ISSUE THREAD

**Issue by danielsousaio** [jhund/filterrific#143]
Hello,

I'm working with other inputs inside form_for_filterrific, and your jquery listens for every input event. I believe that should not be the case, instead you could target only inputs that have names starting with filterrific.

Scenario for your thoughts:
- I have a range slider for prices. I don't want that filterrific sends an ajax request each time the event triggers. Instead I want to delay the event being sent until the user stopped "touching" for 500ms or similar.

Ideas and solutions:
- Target only inputs with name starting by filterrific.
    ":input[name^='filterrific']",

- Allow the periodically observable class to have another complementary class or data attribute to specify a delay for this scenarios.

https://github.com/jhund/filterrific/blob/d1d533cbbe88007dc10bbc251db01a0756573db9/app/assets/javascripts/filterrific/filterrific-jquery.js#L85

**Comment by ddnexus** [comment]
+1

**Comment by gioch** [comment]
Any update on this ? issue is opened `Sep 5, 2017`.

**Comment by danielsousaio** [comment]
@jhund would love to close this issue, any thoughts?

**Comment by cartond** [comment]
You can write your own logic by specifying a different ID like so:
`= form_for_filterrific @filterrific, { html: { id: 'foobar' } } do |f|`

Then in your js, something like
``` 
$('#foobar').on(
    ":input",
    Filterrific.submitFilterForm
);
```
