### ISSUE TITLE
undefined method #deep_stringify_keys for ActionController::Parameters

### ISSUE THREAD

**Issue by RavenXce** [jhund/filterrific#150]
The latest update causes the error in title to be thrown when passing `params[:filterrific]` to `#initialize_filterrific` as AC params does not support `deep_stringify_keys`.

The line(s) of code causing this starts here: https://github.com/jhund/filterrific/commit/73f2ad3c413abf7f6b9945d58735679822ead823#diff-b25115548dd0a89ab586eeaf952d1d12R30.

**Comment by ntbnnt** [comment]
I'm also seeing this issue on Rails 5.1.4

**Comment by jhund** [comment]
@RavenXce thanks for reporting this. I just released a new version that fixes the issue.
