### ISSUE TITLE
5.2 broken for array filters on RubyGems, but not GitHub

### ISSUE THREAD

**Issue by qapn** [jhund/filterrific#186]
Hello! I've come across a minor issue - the version of 5.2 released on RubyGems is not the same as the version of 5.2 on GitHub.

With the RubyGems version, array based filters do not work, but with the GitHub version, they do.

There's a small change on RubyGems to lib/filterrific/param_set.rb line 99 that I think is responsible for the issue.

RubyGems 5.2:
`fp[key] = fp[key].map { |e| e =~ integer_detector_regex ? e.to_i : e }.find_all { |e| }`

GitHub 5.2:
`fp[key] = fp[key].map { |e| e =~ integer_detector_regex ? e.to_i : e }`

I would offer a pull request, but everything is fine on GitHub.

PS, love your gem and all the work you've done on it, thanks heaps!

**Comment by jhund** [comment]
@qapn thanks for the report. What error do you get? Can you please provide me with a scenario to reproduce the issue?

**Comment by jhund** [comment]
This was caused by having some uncommitted code being pushed to rubygems. I just released 5.2.1 to address the issue.

**Comment by qapn** [comment]
@jhund thanks for the lightning fast fix!
