### ISSUE TITLE
Filterrific not working properly with multiple set true

### ISSUE THREAD

**Issue by pacMakaveli** [jhund/filterrific#20]
Hello,

I'm not sure if this is how Filterrific works or if I'm doing something wrong.

I have two `select` tags set as `multiple: true` . When filterrific submits the data through ajax it takes the value from all the selects, which is fine. But if one of them is untouched/default it takes the value as `nil` .. which causes the results to return empty.

![screen shot 2014-10-30 at 2 42 40 pm](https://cloud.githubusercontent.com/assets/894272/4845289/07f7942e-6043-11e4-9e11-f16230fea42f.png)

^ No matter if I touch the `client` select or not, it submits as `nil` .

If both `selects` are normal, with single value, works fine. The issue only happens when it has multiple values. Even by selecting - Any - as default doesn't return as it should.

I basically want to be able to search all my projects that have status `Live` from all clients.

**Comment by jackjackattack23** [comment]
I'm trying something similar with a multi select and no matter what I try, I keep getting this error.  
Rack::Utils::ParameterTypeError - expected Array (got String) for param `with_general_education':
My goal is to be able to filter on more than one general education value and have the sql statement have LIKEs for the general_education column in courses.

Here's my html

 <%= f.select(:with_general_education, @filterrific.select_options[:with_general_education], { include_hidden: false, include_blank: '- Any -' }, multiple: true)%>

<select multiple="multiple" name="filterrific[with_general_education][]" id="filterrific_with_general_education"><option value="">- Any -</option>
<option selected="selected" value="American History">American History</option>
<option value="Basic Communication">Basic Communication</option>
<option value="Foreign Language">Foreign Language</option>
<option value="Humanities">Humanities</option>
<option value="Mathematics">Mathematics</option>
<option value="Natural Sciences">Natural Sciences</option>
<option value="Other World Civilizations">Other World Civilizations</option>
<option value="Social Sciences">Social Sciences</option>
<option value="The Arts">The Arts</option>
<option value="Western Civilization">Western Civilization</option></select>

It seems to be having issues with filterrific[with_general_education][], there's an array at the end of it.

Here's my scope in my courses.rb:

  scope :with_general_education,  lambda { |general_educations|
  return nil if general_educations == [""]
    where(general_education: [*general_educations])
    }

I've tried this as a "Search" and "Filter by column values".  Any help you can provide would be great!

Let me know if you need more info.
