### ISSUE TITLE
Rails 7 - still getting the message "This version of Filterrific only works with Rails 5 and 6"

### ISSUE THREAD

**Issue by marvinick** [jhund/filterrific#210]
I'm still getting the message _**This version of Filterrific only works with Rails 5 and 6**_  after upgrading to Rails 7

filterrific (5.2.2) - Gemfile.lock
Rails 7.0.1 
Ruby 3.0.0 (works just fine with Rails 6.1.4 and the gem)

/Users/marvin/.rvm/gems/ruby-3.0.0/gems/bundler-2.2.29/lib/bundler/runtime.rb:63:in `rescue in block (2 levels) in require': There was an error while trying to load the gem 'filterrific'. (Bundler::GemRequireError)
Gem Load Error is: 

This version of Filterrific only works with Rails 5 and 6.
Please see the Filterrific README for the correct version of Filterrific to use with your version of Rails!

Backtrace for gem load error is:
/Users/marvin/.rvm/gems/ruby-3.0.0/gems/filterrific-5.2.2/lib/filterrific.rb:4:in `<main>'
/Users/marvin/.rvm/gems/ruby-3.0.0/gems/bootsnap-1.10.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
/Users/marvin/.rvm/gems/ruby-3.0.0/gems/bootsnap-1.10.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
/Users/marvin/.rvm/gems/ruby-3.0.0/gems/bundler-2.2.29/lib/bundler/runtime.rb:60:in `block (2 levels) in require'
/Users/marvin/.rvm/gems/ruby-3.0.0/gems/bundler-2.2.29/lib/bundler/runtime.rb:55:in `each'
/Users/marvin/.rvm/gems/ruby-3.0.0/gems/bundler-2.2.29/lib/bundler/runtime.rb:55:in `block in require'
/Users/marvin/.rvm/gems/ruby-3.0.0/gems/bundler-2.2.29/lib/bundler/runtime.rb:44:in `each'
/Users/marvin/.rvm/gems/ruby-3.0.0/gems/bundler-2.2.29/lib/bundler/runtime.rb:44:in `require'
/Users/marvin/.rvm/gems/ruby-3.0.0/gems/bundler-2.2.29/lib/bundler.rb:174:in `require'
/Users/marvin/Documents/local/config/application.rb:7:in `<main>'
/Users/marvin/.rvm/gems/ruby-3.0.0/gems/bootsnap-1.10.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
/Users/marvin/.rvm/gems/ruby-3.0.0/gems/bootsnap-1.10.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
/Users/marvin/.rvm/gems/ruby-3.0.0/gems/railties-7.0.2.2/lib/rails/commands/server/server_command.rb:137:in `block in perform'
<internal:kernel>:90:in `tap'
/Users/marvin/.rvm/gems/ruby-3.0.0/gems/railties-7.0.2.2/lib/rails/commands/server/server_command.rb:134:in `perform'
/Users/marvin/.rvm/gems/ruby-3.0.0/gems/thor-1.2.1/lib/thor/command.rb:27:in `run'
/Users/marvin/.rvm/gems/ruby-3.0.0/gems/thor-1.2.1/lib/thor/invocation.rb:127:in `invoke_command'
/Users/marvin/.rvm/gems/ruby-3.0.0/gems/thor-1.2.1/lib/thor.rb:392:in `dispatch'
/Users/marvin/.rvm/gems/ruby-3.0.0/gems/railties-7.0.2.2/lib/rails/command/base.rb:87:in `perform'
/Users/marvin/.rvm/gems/ruby-3.0.0/gems/railties-7.0.2.2/lib/rails/command.rb:48:in `invoke'
/Users/marvin/.rvm/gems/ruby-3.0.0/gems/railties-7.0.2.2/lib/rails/commands.rb:18:in `<main>'
/Users/marvin/.rvm/gems/ruby-3.0.0/gems/bootsnap-1.10.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
/Users/marvin/.rvm/gems/ruby-3.0.0/gems/bootsnap-1.10.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
/Users/marvin/Documents/local/bin/rails:9:in `<top (required)>'
/Users/marvin/.rvm/gems/ruby-3.0.0/gems/spring-2.1.1/lib/spring/client/rails.rb:28:in `load'
/Users/marvin/.rvm/gems/ruby-3.0.0/gems/spring-2.1.1/lib/spring/client/rails.rb:28:in `call'
/Users/marvin/.rvm/gems/ruby-3.0.0/gems/spring-2.1.1/lib/spring/client/command.rb:7:in `call'
/Users/marvin/.rvm/gems/ruby-3.0.0/gems/spring-2.1.1/lib/spring/client.rb:30:in `run'
/Users/marvin/.rvm/gems/ruby-3.0.0/gems/spring-2.1.1/bin/spring:49:in `<top (required)>'
/Users/marvin/.rvm/gems/ruby-3.0.0/gems/spring-2.1.1/lib/spring/binstub.rb:11:in `load'
/Users/marvin/.rvm/gems/ruby-3.0.0/gems/spring-2.1.1/lib/spring/binstub.rb:11:in `<top (required)>'
<internal:/Users/marvin/.rvm/rubies/ruby-3.0.0/lib/ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
<internal:/Users/marvin/.rvm/rubies/ruby-3.0.0/lib/ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
/Users/marvin/Documents/local/bin/spring:15:in `<top (required)>'
bin/rails:3:in `load'
bin/rails:3:in `<main>'
Bundler Error Backtrace:
	from /Users/marvin/.rvm/gems/ruby-3.0.0/gems/bundler-2.2.29/lib/bundler/runtime.rb:59:in `block (2 levels) in require'
	from /Users/marvin/.rvm/gems/ruby-3.0.0/gems/bundler-2.2.29/lib/bundler/runtime.rb:55:in `each'
	from /Users/marvin/.rvm/gems/ruby-3.0.0/gems/bundler-2.2.29/lib/bundler/runtime.rb:55:in `block in require'
	from /Users/marvin/.rvm/gems/ruby-3.0.0/gems/bundler-2.2.29/lib/bundler/runtime.rb:44:in `each'
	from /Users/marvin/.rvm/gems/ruby-3.0.0/gems/bundler-2.2.29/lib/bundler/runtime.rb:44:in `require'
	from /Users/marvin/.rvm/gems/ruby-3.0.0/gems/bundler-2.2.29/lib/bundler.rb:174:in `require'
	from /Users/marvin/Documents/local/config/application.rb:7:in `<main>'
	from /Users/marvin/.rvm/gems/ruby-3.0.0/gems/bootsnap-1.10.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
	from /Users/marvin/.rvm/gems/ruby-3.0.0/gems/bootsnap-1.10.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
	from /Users/marvin/.rvm/gems/ruby-3.0.0/gems/railties-7.0.2.2/lib/rails/commands/server/server_command.rb:137:in `block in perform'
	from <internal:kernel>:90:in `tap'
	from /Users/marvin/.rvm/gems/ruby-3.0.0/gems/railties-7.0.2.2/lib/rails/commands/server/server_command.rb:134:in `perform'
	from /Users/marvin/.rvm/gems/ruby-3.0.0/gems/thor-1.2.1/lib/thor/command.rb:27:in `run'
	from /Users/marvin/.rvm/gems/ruby-3.0.0/gems/thor-1.2.1/lib/thor/invocation.rb:127:in `invoke_command'
	from /Users/marvin/.rvm/gems/ruby-3.0.0/gems/thor-1.2.1/lib/thor.rb:392:in `dispatch'
	from /Users/marvin/.rvm/gems/ruby-3.0.0/gems/railties-7.0.2.2/lib/rails/command/base.rb:87:in `perform'
	from /Users/marvin/.rvm/gems/ruby-3.0.0/gems/railties-7.0.2.2/lib/rails/command.rb:48:in `invoke'
	from /Users/marvin/.rvm/gems/ruby-3.0.0/gems/railties-7.0.2.2/lib/rails/commands.rb:18:in `<main>'
	from /Users/marvin/.rvm/gems/ruby-3.0.0/gems/bootsnap-1.10.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
	from /Users/marvin/.rvm/gems/ruby-3.0.0/gems/bootsnap-1.10.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
	from /Users/marvin/Documents/local/bin/rails:9:in `<top (required)>'
	from /Users/marvin/.rvm/gems/ruby-3.0.0/gems/spring-2.1.1/lib/spring/client/rails.rb:28:in `load'
	from /Users/marvin/.rvm/gems/ruby-3.0.0/gems/spring-2.1.1/lib/spring/client/rails.rb:28:in `call'
	from /Users/marvin/.rvm/gems/ruby-3.0.0/gems/spring-2.1.1/lib/spring/client/command.rb:7:in `call'
	from /Users/marvin/.rvm/gems/ruby-3.0.0/gems/spring-2.1.1/lib/spring/client.rb:30:in `run'
	from /Users/marvin/.rvm/gems/ruby-3.0.0/gems/spring-2.1.1/bin/spring:49:in `<top (required)>'
	from /Users/marvin/.rvm/gems/ruby-3.0.0/gems/spring-2.1.1/lib/spring/binstub.rb:11:in `load'
	from /Users/marvin/.rvm/gems/ruby-3.0.0/gems/spring-2.1.1/lib/spring/binstub.rb:11:in `<top (required)>'
	from <internal:/Users/marvin/.rvm/rubies/ruby-3.0.0/lib/ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
	from <internal:/Users/marvin/.rvm/rubies/ruby-3.0.0/lib/ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
	from /Users/marvin/Documents/local/bin/spring:15:in `<top (required)>'
	from bin/rails:3:in `load'
	from bin/rails:3:in `<main>'
/Users/marvin/.rvm/gems/ruby-3.0.0/gems/filterrific-5.2.2/lib/filterrific.rb:4:in `<main>':  (RuntimeError)

This version of Filterrific only works with Rails 5 and 6.
Please see the Filterrific README for the correct version of Filterrific to use with your version of Rails!

	from /Users/marvin/.rvm/gems/ruby-3.0.0/gems/bootsnap-1.10.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
	from /Users/marvin/.rvm/gems/ruby-3.0.0/gems/bootsnap-1.10.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
	from /Users/marvin/.rvm/gems/ruby-3.0.0/gems/bundler-2.2.29/lib/bundler/runtime.rb:60:in `block (2 levels) in require'
	from /Users/marvin/.rvm/gems/ruby-3.0.0/gems/bundler-2.2.29/lib/bundler/runtime.rb:55:in `each'
	from /Users/marvin/.rvm/gems/ruby-3.0.0/gems/bundler-2.2.29/lib/bundler/runtime.rb:55:in `block in require'
	from /Users/marvin/.rvm/gems/ruby-3.0.0/gems/bundler-2.2.29/lib/bundler/runtime.rb:44:in `each'
	from /Users/marvin/.rvm/gems/ruby-3.0.0/gems/bundler-2.2.29/lib/bundler/runtime.rb:44:in `require'
	from /Users/marvin/.rvm/gems/ruby-3.0.0/gems/bundler-2.2.29/lib/bundler.rb:174:in `require'
	from /Users/marvin/Documents/local/config/application.rb:7:in `<main>'
	from /Users/marvin/.rvm/gems/ruby-3.0.0/gems/bootsnap-1.10.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
	from /Users/marvin/.rvm/gems/ruby-3.0.0/gems/bootsnap-1.10.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
	from /Users/marvin/.rvm/gems/ruby-3.0.0/gems/railties-7.0.2.2/lib/rails/commands/server/server_command.rb:137:in `block in perform'
	from <internal:kernel>:90:in `tap'
	from /Users/marvin/.rvm/gems/ruby-3.0.0/gems/railties-7.0.2.2/lib/rails/commands/server/server_command.rb:134:in `perform'
	from /Users/marvin/.rvm/gems/ruby-3.0.0/gems/thor-1.2.1/lib/thor/command.rb:27:in `run'
	from /Users/marvin/.rvm/gems/ruby-3.0.0/gems/thor-1.2.1/lib/thor/invocation.rb:127:in `invoke_command'
	from /Users/marvin/.rvm/gems/ruby-3.0.0/gems/thor-1.2.1/lib/thor.rb:392:in `dispatch'
	from /Users/marvin/.rvm/gems/ruby-3.0.0/gems/railties-7.0.2.2/lib/rails/command/base.rb:87:in `perform'
	from /Users/marvin/.rvm/gems/ruby-3.0.0/gems/railties-7.0.2.2/lib/rails/command.rb:48:in `invoke'
	from /Users/marvin/.rvm/gems/ruby-3.0.0/gems/railties-7.0.2.2/lib/rails/commands.rb:18:in `<main>'
	from /Users/marvin/.rvm/gems/ruby-3.0.0/gems/bootsnap-1.10.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
	from /Users/marvin/.rvm/gems/ruby-3.0.0/gems/bootsnap-1.10.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
	from /Users/marvin/Documents/local/bin/rails:9:in `<top (required)>'
	from /Users/marvin/.rvm/gems/ruby-3.0.0/gems/spring-2.1.1/lib/spring/client/rails.rb:28:in `load'
	from /Users/marvin/.rvm/gems/ruby-3.0.0/gems/spring-2.1.1/lib/spring/client/rails.rb:28:in `call'
	from /Users/marvin/.rvm/gems/ruby-3.0.0/gems/spring-2.1.1/lib/spring/client/command.rb:7:in `call'
	from /Users/marvin/.rvm/gems/ruby-3.0.0/gems/spring-2.1.1/lib/spring/client.rb:30:in `run'
	from /Users/marvin/.rvm/gems/ruby-3.0.0/gems/spring-2.1.1/bin/spring:49:in `<top (required)>'
	from /Users/marvin/.rvm/gems/ruby-3.0.0/gems/spring-2.1.1/lib/spring/binstub.rb:11:in `load'
	from /Users/marvin/.rvm/gems/ruby-3.0.0/gems/spring-2.1.1/lib/spring/binstub.rb:11:in `<top (required)>'
	from <internal:/Users/marvin/.rvm/rubies/ruby-3.0.0/lib/ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
	from <internal:/Users/marvin/.rvm/rubies/ruby-3.0.0/lib/ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
	from /Users/marvin/Documents/local/bin/spring:15:in `<top (required)>'
	from bin/rails:3:in `load'
	from bin/rails:3:in `<main>'

**Comment by lucashaley** [comment]
Same:

filterrific (5.2.2)
rails (7.0.2)
ruby (2.7.4p191)

Thank you!

**Comment by GearoidDC** [comment]
If you fork your own branch it'll work straight away without any changes.

The changes are there in 5.2.2 to allow Rails 7 to run but don't have any impact for some reason when pulled from the main branch?

**Comment by marvinick** [comment]
This is no longer an issue when installing directly from the source: 

gem 'filterrific', git: 'https://github.com/jhund/filterrific'

Thanks @GearoidDC
