### ISSUE TITLE
Chainning the existing scopes with Filterrific doesn't work when the filter is empty.

### ISSUE THREAD

**Issue by vmeyet** [jhund/filterrific#28]
Chainning the existing scopes with Filterrific doesn't work when the filter is empty.

Here is a simple example:

```ruby
# Assuming a feedback model having a rating (integer) column
class Feedback < ActiveRecord::Base
  filterrific(filter_names: [:with_rating])
  scope :no_low_rating, -> { where('rating > ?', 2) }
  scope :with_rating, ->(keys) { where(rating: [*keys.to_s.split(',')]) }
end

# When there is a filter
filter = Filterrific.new(Feedback, with_rating: 2)
# This will work
Feedback.no_low_rating.filterrific_find(filter)
# When there is no filter
filter = Filterrific.new(Feedback, {})
# This won't work, it'll give me the ActiveRecord class Feedback
Feedback.no_low_rating.filterrific_find(filter)
# This will work but is damn ugly
Feedback.filterrific_find(filter).all.scoping { Feedback.no_low_rating }
```

A fix seems to be the following (ruby 2.0.0 rails 4.1)

```ruby
module Filterrific
  module ActiveRecordExtension
    def filterrific_find(filterrific_param_set)
      unless filterrific_param_set.is_a?(Filterrific::ParamSet)
        raise(ArgumentError, "Invalid Filterrific::ParamSet: #{ filterrific_param_set.inspect }")
      end

      # set initial ar_proxy to including class
      ar_proxy = self.all  # CHANGED `self` TO `self.all`

      # apply filterrific params
      self.filterrific_filter_names.each do |filter_name|
        filter_param = filterrific_param_set.send(filter_name)
        next if filter_param.blank? # skip blank filter_params
        ar_proxy = ar_proxy.send(filter_name, filter_param)
      end

      ar_proxy
    end
  end
end
```

It's seems to work for the other cases:
  - when the filter isn't empty,
  - or when you apply the second scope afterward

**Comment by jhund** [comment]
@vmeyet thank you for using filterrific and for bringing this to my attention. Your proposed solution works for Rails 4. It requires a slightly different approach in Rails 3. I have sketched out the code and will test it, then cut a new release very soon.

**Comment by vmeyet** [comment]
@jhund, indeed I'm new to rails and have only worked with rails 4 so far. I'm missed that. Anyway thanks for the soon-to-be-release fix.

**Comment by jhund** [comment]
@vmeyet I released version 1.4.3 that fixes the issue.

**Comment by vmeyet** [comment]
Saw the fix! thanks

**Comment by jquiu** [comment]
thank you very much, had been fighting for with this problem for a week

**Comment by bjensen** [comment]
How is this issue solved?

I have this: 

 @filterrific = initialize_filterrific(Stay, params[:filterrific_stays]) or return
@stays = current_school.stays.includes(:stay_type, :termination).joins(student: :profile).where("stays.id IN (?)", @workshop.current_attendance_ids).filterrific_find(@filterrific) 

However sorting doesn't work. Im using the newest version of filterrific..

**Comment by jhund** [comment]
@bjensen do other filters work? Just no the sorting?

I need more info to figure out what's going on:

* I notice that you changed the filterrific param name to :filterrific_stays. This may cause issues if you don't handle it consistenly in all places (views and controllers). However if this were the cause, no filtering would work. It sounds like only sorting doesn't work?
* can you post the value of `params[:filterrific_stays]`
* what do your associations look like between Stay, StayType, Student, Workshop, and School ?
* can you post the entire code for StaysController#index?
