### ISSUE TITLE
Search button

### ISSUE THREAD

**Issue by spawnge** [jhund/filterrific#31]
Hi, first of all I'd like like to thank you for this great gem. I'm actually looking for a way to perform searches with a search button only. I have too many input fields and a google maps in my _list partial, having a new request each time a select input has been changed isn't a good thing I guess. How can I implement a button ? Thanks in advance for your answer

**Comment by jhund** [comment]
@spawnge see below for steps to use filterrific without ajax auto submit:

This is what you use in your view (based on Filterrific 2.x):

~~~ erb
<%= form_for_filterrific @filterrific, html: { id: 'filterrific-no-ajax-auto-submit' } do |f| %>
...
  <%= f.submit 'Filter' %>
<% end%>
~~~

Also make sure not to assign the `.filterrific-periodically-observed` class to any inputs.

**Comment by spawnge** [comment]
Sorry for the late response I forgot to come back to this issue, your solution works perfectly. I was just wondering if there's a way to do the same thing using ajax (which is more reactive than a page reload) ? Thanks a lot for everything.

**Comment by jhund** [comment]
@spawnge why don't you try adding `remote: true` to the options passed to `form_for`? That should do the trick.

**Comment by jhund** [comment]
@spawnge sorry, clarification, add `remote: true` to `form_for_filterrific`, not `form_for`.

**Comment by spawnge** [comment]
A hundred thanks that's working ! :)

**Comment by jhund** [comment]
Great, thanks for using filterrific!
