### ISSUE TITLE
Initial DB setup question

### ISSUE THREAD

**Issue by mandym-webdev** [jhund/filterrific#33]
Hi, 

I want to use filterrific on a new project but I want to make sure that I set the database up correctly.

I want my users to be able to input which language(s) they speak.  ex: User 1 speaks English, French, Spanish. 

I want people to be able to filter the search using multiple languages. Ex: find all users that speak both English and Spanish.  I figured that would be done via a drop-down with check boxes.

What is the best way to set this up so that search/filtering is as fast as possible?  Should each language be in a separate field ex: language_1 contains English, language_2 contains Spanish, etc. or can I save the languages in an array under a single field ex: language contains [English, Spanish, French]

Thanks for any feedback.  I am just building out the app and don't want to get too far down a path that might make things slow.

**Comment by jhund** [comment]
@mandym-webdev thanks for using filterrific. Based on what you describe, here is how I would set it up:

~~~ ruby
class User < ActiveRecord::Base
  has_many :spoken_languages
  has_many :languages, through: :spoken_languages
end

# Use a join table to create a many-to-many association between
# User and Language. In human words:
# Each User can speak many Languages and
# each Language can be spoken by many Users.
class SpokenLanguage < ActiveRecord::Base
  belongs_to :language
  belongs_to :user
end

class Language < ActiveRecord::Base
  has_many :spoken_languages
  has_many :users, through: :spoken_languages
end
~~~

Then for filterrific, you are looking for an AND condition of several spoken languages. The appropriate control in the UI would be a multi-select list, or a checkbox array of Languages. I like to use [chosen.js](http://harvesthq.github.io/chosen/#multiple-select) for this purpose.

And finally the ActiveRecord scope on the User model, based on the [awesome filterrific documentation](http://filterrific.clearcove.ca/pages/active_record_scope_patterns.html#filter_by_existence_many_to_many) would look like this:

~~~ ruby
class User < ActiveRecord::Base
  scope :with_all_language_ids, lambda{ |language_ids|
    # get a reference to the join table
    spoken_languages = SpokenLanguage.arel_table
    # get a reference to the filtered table
    users = User.arel_table
    # let AREL generate a complex SQL query
    language_ids.map(&:to_i).inject(self) { |rel, language_id|
      rel.where(
        SpokenLanguage \
          .where(spoken_languages[:user_id].eq(users[:id])) \
          .where(spoken_languages[:language_id].eq(language_id)) \
          .exists
      )
    }
  }
end
~~~
