### ISSUE TITLE
Passing filter parameters in a url?

### ISSUE THREAD

**Issue by jackjackattack23** [jhund/filterrific#35]
I hoping to use this gem to replace our current filtering system because it looks really awesome.  The one thing that we need to be able to do is pass filter parameters in to that page through a url.  That way we can send a user to the exact set of results they may be looking for.  Is there a way to add ?search_query=Chris or whatever to the end of the page url?

**Comment by jackjackattack23** [comment]
I think I just stumbled across a solution.  Add on something like this 
?filterrific[search_query]=credit&filterrific[with_school_id]=2.  Is this the best way to achieve this?

**Comment by jhund** [comment]
@jackjackattack23 yes, what you posted is the correct way to handle it. Filterrific looks for the `filterrific` key in the request's `params` object.
