### ISSUE TITLE
Disable Auto-populate at page load?

### ISSUE THREAD

**Issue by CIRailsStation** [jhund/filterrific#36]
Hi there - love your gem!  I would like to use it with a db with about 100k entires, however I would like for all those entries to not auto-populate as soon as the index.html.erb page is loaded; only after a user has entered their search/sort criteria, and if the filters are reset the results would again clear. 

I've tried playing with the controller code in an attempt to prevent `@inst_var = @filterrific.find.page(params[:page])` from populating right away, but have only succeeded in breaking the code over and again. Any advice is welcomed. Thanks!

**Comment by jhund** [comment]
@CIRailsStation what's the reason for not wanting to load the records? Are you concerned that loading 100K records explodes your server? If so, wouldn't pagination prevent loading too many records?

What may work for you is something I'm currently working on where you can check if any @filterrific filters other than the defaults have been applied. I should be able to release it in the next few days. You'd use it like so in the controller:

~~~ ruby
@records = @filterrific.has_filters_applied? ? @filterrific.find.page(params[:page]) : []
~~~

**Comment by CIRailsStation** [comment]
Nice! I'll check back in the next couple days. 

I completely overlooked that pagination is already limiting the entries that get loaded. it's been a long week :) Thanks!
