### ISSUE TITLE
many-to-many filter in view

### ISSUE THREAD

**Issue by ninjonxb** [jhund/filterrific#37]
I have been trying to figure out the view necessary to make the many-to-many relation work and I can't figure it out.  
I have the scope working (tested by setting default values).  
I am using the scope mentioned here http://filterrific.clearcove.ca/pages/active_record_scope_patterns.html#filter_by_existence_many_to_many

I am trying to either have checkboxes or a multi select list. 

I can't seem to find an answer anywhere else online.

**Comment by jhund** [comment]
@ninjonxb I'm not sure what you're trying to accomplish. Could you please provide your models (at least the names and how they are associated: has_many, belongs_to, etc.), and what exactly you're trying to filter for.

**Comment by ninjonxb** [comment]
```
	scope :with_any_category_ids, lambda{ |category_ids|
	  # get a reference to the join table
	  catagrelations = Catagrelation.arel_table
	  # get a reference to the filtered table
	  cartelitems = Cartelitem.arel_table
	  # let AREL generate a complex SQL query
	  where(
	    Catagrelation \
	      .where(catagrelations[:cartelitem_id].eq(cartelitems[:id])) \
	      .where(catagrelations[:catagory_id].in([*category_ids].map(&:to_i))) \
	      .exists
	  )
	}
```

```
	has_many :catagrelations
  	has_many :catagories, through: :catagrelations
```

This code works perfectly. I can test it by adding 
```
with_any_category_ids: [1,2]
```
to my default_filter_params and it does what I need.  
What I can't figure out is how make the view work to send the values.  There isn't an example in the documentation. Only an example of the scope.

Jon

**Comment by jhund** [comment]
@ninjonxb the view API is documented in the [Filterrific documentation](http://filterrific.clearcove.ca/pages/action_view_api.html). You can just follow the examples for `:country_id` and transfer them to your filter `:with_any_category_ids`. Here is what I'd use:

~~~ erb
<%= f.select(
  :with_any_category_ids,
  @filterrific.select_options[:with_any_category_ids],
  { include_blank: '- Any -' },
  { multiple: true }
) %>
~~~

Make sure to initialize `@filterrific.select_options[:with_any_category_ids]` with a list of your categories.
