### ISSUE TITLE
Dynamic filters on hstore params?

### ISSUE THREAD

**Issue by alankessler** [jhund/filterrific#43]
@jhund I'm having some trouble wrapping my head around how I would do this. I want my model to have an hstore with user-configurable fields. I then want the user to be able to filter on each field. Can it work?

Thanks!

**Comment by alankessler** [comment]
here's what I have so far:
model:
```
  store_accessor :properties
...
  scope :with_properties, lambda{|phash| query_array = [] ;
                                         argument_hash = {};
                                         phash.each_with_index do |(key,value),index|
                                           query_array << "properties -> :key_#{index} @@ :value_#{index}";
                                           argument_hash = argument_hash.merge("key_#{index}".to_sym => key, "value_#{index}".to_sym => value );
                                         end; 
                                         where(query_string = query_array.join(' AND '), argument_hash)
                                }

```
view:
``` <%= f.fields_for :with_properties do |g| %>```

This seems to work just fine :)  ... however, I'd love feedback on whether there's a better way. If not, this might be good material for the documentation.

**Comment by jhund** [comment]
@alankessler thanks for posting your recipe. I haven't used hstore yet, however it sounds like a cool feature. I reformatted your code a bit and I think it looks good: You're sanitizing the SQL params and you're dropping empty values.

~~~ ruby
store_accessor :properties # can you call this method without additional arguments?

scope :with_properties, ->(phash) {
  query_array = []
  argument_hash = {}
  phash.each_with_index do |(key,value),index|
    if value.present?
      query_array << "properties -> :key_#{index} @@ :value_#{index}"
      argument_hash = argument_hash.merge(
        "key_#{ index }".to_sym => key, 
        "value_#{ index }".to_sym => value
      )
    end
  end
  where(
    query_string = query_array.join(' AND '), 
    argument_hash
  )
}
~~~

**Comment by alankessler** [comment]
@jhund thank you for cleaning that up; it's much nicer to read. 

I think the argument to store_accessor is just a list of pre-defined keys, but I don't have any for this project. I am running it like noted above and it seems to work.

**Comment by alankessler** [comment]
In case someone happens to use this; with 2.0 I had to convert the OpenStruct back to a hash... this code makes it work again:

                                         if phash.is_a?(OpenStruct)
                                           hash = phash.marshal_dump
                                         else
                                           hash = phash

**Comment by jhund** [comment]
@alankessler I'm considering removing the cast to OpenStruct for Hashes. The reason for this was so that form inputs would show the previously selected values for nested hashes. However it doesn't work anyways. I found out that I have to cast the filterrific attribute to an OpenStruct in the view to make it work for nested filters. Just a heads up that this may come soon.

**Comment by alankessler** [comment]
Thanks for the warning.
