### ISSUE TITLE
Filter by nil value

### ISSUE THREAD

**Issue by fist28** [jhund/filterrific#46]
I use multiple select for filter by status and I would like to add option "by blank'. 
But when I add `['by blank', nil]` to collection then in html i have blank value in option element.

I have workaround solution, I add  `['by blank', 'nil']` to collection and in scope replace `'nil'` to `nil`. 
scope: 
```ruby
  scope :with_status_id, lambda { |status_ids|
    ids = status_ids.dup 
    idx = status_ids.index { |o| o == 'nil' }
    ids[idx] = nil unless idx.nil?
    where(status_id: [*ids]) unless ids == [""]
  }
```
Is there any better way to filter by `nil` value?

**Comment by jhund** [comment]
@fist28 your approach is very similar to what I would do:

~~~ ruby
scope :with_status_id, lambda { |status_ids|
  return nil  if status_ids.blank? # replaces `unless` clause in last line of your example
  ids = status_ids.map { |e| 'nil' == e ? nil : e } # replaces first three lines in your example
  where(status_id: [*ids])
end
~~~

The only thing I'm not sure about is if ActiveRecord is smart enough to handle the nil value correctly when it generates the SQL query. The syntax for null values is different in WHERE clauses:

~~~
WHERE status_id IS NULL
 vs.
WHERE status_id = 1
~~~

**Comment by jhund** [comment]
No response, closing issue.
