### ISSUE TITLE
join 2 or more tables with unique filters

### ISSUE THREAD

**Issue by ninjonxb** [jhund/filterrific#47]
I am not sure if what I want to do is even possible with filterific.  
I am currently looking into building a single unified search for my website.  
This would hit a few different tables with different types of data.  
Ideally what I could do is be able to do is have the scopes for each in the their model and then in the controller for the unified search it would be able to do queries against all of the models based on their relevant options and then combine all of the data.  
Then in my view I would just check the type of object it is to determine how it displays in the search.  

I am not sure if this is possible with filterific, I can't find any examples of this working anywhere else. 

Thanks

**Comment by jhund** [comment]
@ninjonxb without knowing the types of tables you're trying to search, it's hard to provide any feedback. 

You could run multiple database queries in your controller action, one for each table you want to search. I would instantiate a filterrific object for each class, and use that to run a DB query.

I would avoid merging the different objects into a single stream, esp. if you are doing pagination. Can you display them grouped by class?

Thanks for using filterrific.

**Comment by jhund** [comment]
No response, closing issue.
