### ISSUE TITLE
undefined method `sorted_by' for #<Student::ActiveRecord_Relation:0x007ff436318418>

### ISSUE THREAD

**Issue by birchlore** [jhund/filterrific#52]
I followed the exact setup steps in the example and getting the above error message. Any ideas why this might be happening?

Student.rb

  ```class Student < ActiveRecord::Base
 belongs_to :user
 has_many :assessments
  attr_accessor :referer
  
  filterrific(
  default_filter_params: { sorted_by: 'created_at_desc' },
  available_filters: [
    :sorted_by,
    :search_query,
    :with_created_at_gte
  ]
    )
```

Student controller:

  ```def index
    @patients = current_user.patients.sort_by &:first_name

    @filterrific = initialize_filterrific(
      Patient,
      params[:filterrific]
    ) or return
     @patients = @filterrific.find.page(params[:page])

    respond_to do |format|
      format.html
      format.js
    end
  end
```

**Comment by jhund** [comment]
@birchlore I don't see the scope definition for :sorted_by in your model code. If it's not in your app, then this would explain the error message.

See the [documentation](http://filterrific.clearcove.ca/pages/active_record_scope_patterns.html#sort) for example code.

**Comment by birchlore** [comment]
Ah, missed that part. Thanks for the quick response

**Comment by jhund** [comment]
Thanks for using Filterrific!
