### ISSUE TITLE
Direct to filter page with params

### ISSUE THREAD

**Issue by ozhe** [jhund/filterrific#56]
I have two views. The first one runs filterrific with a text input and a select input. The second view has a text input and a button. I want the button to link to the first view with the input value passed to the filter. However, when I set the initial value of the filter input, filterrific observer doesn't detect it. I need to update the text input again to make the page show the correct result. 

    <%= f.text_field(:search_query, :value => params[:q], class: 'filterrific-periodically-observed typeahead') %>

**Comment by jhund** [comment]
@ozhe I would modify the first form (with text input) so that it does the following:

* name the text input in the non-filterrific view the same as the field you want to populate on the filterrific view
* change the non-filterrific view to submit to your filterrific action via get

Filterrific will then pick up the filter param and pre-populate the list correctly.

**Comment by ozhe** [comment]
I changed the non-filterrific view input name to "filterrific[search_query]" and it worked!
Thank you!

**Comment by ozhe** [comment]
A follow-up question. Since I change the name of my text input to `filterrific[search_query]`. How could I use the value of it out of filterrific form builder. `params[filterrific[search_query]]` seems not working.

**Comment by alankessler** [comment]
Try params[filterrific][search_query] instead

These support level questions are not issues with the gem. In fact, this
was really just a Rails or even a Ruby question.

It would be much better if you would post them on StackOverflow so as not
to use up jhund's resources and so as to give the gem more exposure to the
programming community.

http://stackoverflow.com/

**Comment by ozhe** [comment]
@alankessler sorry about that. I'll use stackoverflow if I encounter more questions. Thank you for the answer anyway!
