### ISSUE TITLE
Add sort to headers

### ISSUE THREAD

**Issue by aaronchi** [jhund/filterrific#57]
We're using https://github.com/Sology/smart_listing right now for our lists. I like the simplicity of this gem but the one thing it is missing is sortable headers. Any chance you are planning to add this feature?

**Comment by alankessler** [comment]
It already exists (unless I misunderstand). filterrific_sorting_link

https://www.omniref.com/ruby/gems/filterrific/1.4.0/symbols/Filterrific::ActionViewExtension/filterrific_sorting_link

I use it, it works well.

**Comment by aaronchi** [comment]
Oh great. Didn't see it on the demo so I assumed it wasn't in there.
