### ISSUE TITLE
undefined method `options_for_select' 

### ISSUE THREAD

**Issue by gcalori** [jhund/filterrific#60]
I'm new in the use of filterrific.
In my application I got the error in the subject.
I'm using
    filterrific (2.0.5)
    rails (4.2.1)
    ruby 1.9.3 p545 on win7

STACK TRACE:

activerecord (4.2.1) lib/active_record/dynamic_matchers.rb:26:in `method_missing'
app/controllers/prevheads_controller.rb:9:in `index'
actionpack (4.2.1) lib/action_controller/metal/implicit_render.rb:4:in `send_action'
actionpack (4.2.1) lib/abstract_controller/base.rb:198:in `process_action'
actionpack (4.2.1) lib/action_controller/metal/rendering.rb:10:in `process_action'
actionpack (4.2.1) lib/abstract_controller/callbacks.rb:20:in `block in process_action'
activesupport (4.2.1) lib/active_support/callbacks.rb:117:in `call'
activesupport (4.2.1) lib/active_support/callbacks.rb:117:in `call'
activesupport (4.2.1) lib/active_support/callbacks.rb:555:in `block (2 levels) in compile'
activesupport (4.2.1) lib/active_support/callbacks.rb:505:in `call'
activesupport (4.2.1) lib/active_support/callbacks.rb:505:in `call'
activesupport (4.2.1) lib/active_support/callbacks.rb:92:in `_run_callbacks'
activesupport (4.2.1) lib/active_support/callbacks.rb:776:in `_run_process_action_callbacks'
activesupport (4.2.1) lib/active_support/callbacks.rb:81:in `run_callbacks'
actionpack (4.2.1) lib/abstract_controller/callbacks.rb:19:in `process_action'
actionpack (4.2.1) lib/action_controller/metal/rescue.rb:29:in `process_action'
actionpack (4.2.1) lib/action_controller/metal/instrumentation.rb:32:in `block in process_action'
activesupport (4.2.1) lib/active_support/notifications.rb:164:in `block in instrument'
activesupport (4.2.1) lib/active_support/notifications/instrumenter.rb:20:in `instrument'
activesupport (4.2.1) lib/active_support/notifications.rb:164:in `instrument'
actionpack (4.2.1) lib/action_controller/metal/instrumentation.rb:30:in `process_action'
actionpack (4.2.1) lib/action_controller/metal/params_wrapper.rb:250:in `process_action'
activerecord (4.2.1) lib/active_record/railties/controller_runtime.rb:18:in `process_action'
actionpack (4.2.1) lib/abstract_controller/base.rb:137:in `process'
actionview (4.2.1) lib/action_view/rendering.rb:30:in `process'
actionpack (4.2.1) lib/action_controller/metal.rb:196:in `dispatch'
actionpack (4.2.1) lib/action_controller/metal/rack_delegation.rb:13:in `dispatch'
actionpack (4.2.1) lib/action_controller/metal.rb:237:in `block in action'
actionpack (4.2.1) lib/action_dispatch/routing/route_set.rb:74:in `call'
actionpack (4.2.1) lib/action_dispatch/routing/route_set.rb:74:in `dispatch'
actionpack (4.2.1) lib/action_dispatch/routing/route_set.rb:43:in `serve'
actionpack (4.2.1) lib/action_dispatch/journey/router.rb:43:in `block in serve'
actionpack (4.2.1) lib/action_dispatch/journey/router.rb:30:in `each'
actionpack (4.2.1) lib/action_dispatch/journey/router.rb:30:in `serve'
actionpack (4.2.1) lib/action_dispatch/routing/route_set.rb:819:in `call'
rack (1.6.1) lib/rack/etag.rb:24:in `call'
rack (1.6.1) lib/rack/conditionalget.rb:25:in `call'
rack (1.6.1) lib/rack/head.rb:13:in `call'
actionpack (4.2.1) lib/action_dispatch/middleware/params_parser.rb:27:in `call'
actionpack (4.2.1) lib/action_dispatch/middleware/flash.rb:260:in `call'
rack (1.6.1) lib/rack/session/abstract/id.rb:225:in `context'
rack (1.6.1) lib/rack/session/abstract/id.rb:220:in `call'
actionpack (4.2.1) lib/action_dispatch/middleware/cookies.rb:560:in `call'
activerecord (4.2.1) lib/active_record/query_cache.rb:36:in `call'
activerecord (4.2.1) lib/active_record/connection_adapters/abstract/connection_pool.rb:649:in `call'
activerecord (4.2.1) lib/active_record/migration.rb:378:in `call'
actionpack (4.2.1) lib/action_dispatch/middleware/callbacks.rb:29:in `block in call'
activesupport (4.2.1) lib/active_support/callbacks.rb:88:in `call'
activesupport (4.2.1) lib/active_support/callbacks.rb:88:in `_run_callbacks'
activesupport (4.2.1) lib/active_support/callbacks.rb:776:in `_run_call_callbacks'
activesupport (4.2.1) lib/active_support/callbacks.rb:81:in `run_callbacks'
actionpack (4.2.1) lib/action_dispatch/middleware/callbacks.rb:27:in `call'
actionpack (4.2.1) lib/action_dispatch/middleware/reloader.rb:73:in `call'
actionpack (4.2.1) lib/action_dispatch/middleware/remote_ip.rb:78:in `call'
actionpack (4.2.1) lib/action_dispatch/middleware/debug_exceptions.rb:17:in `call'
web-console (2.1.2) lib/web_console/middleware.rb:37:in `call'
actionpack (4.2.1) lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'
railties (4.2.1) lib/rails/rack/logger.rb:38:in `call_app'
railties (4.2.1) lib/rails/rack/logger.rb:20:in `block in call'
activesupport (4.2.1) lib/active_support/tagged_logging.rb:68:in `block in tagged'
activesupport (4.2.1) lib/active_support/tagged_logging.rb:26:in `tagged'
activesupport (4.2.1) lib/active_support/tagged_logging.rb:68:in `tagged'
railties (4.2.1) lib/rails/rack/logger.rb:20:in `call'
actionpack (4.2.1) lib/action_dispatch/middleware/request_id.rb:21:in `call'
rack (1.6.1) lib/rack/methodoverride.rb:22:in `call'
rack (1.6.1) lib/rack/runtime.rb:18:in `call'
activesupport (4.2.1) lib/active_support/cache/strategy/local_cache_middleware.rb:28:in `call'
rack (1.6.1) lib/rack/lock.rb:17:in `call'
actionpack (4.2.1) lib/action_dispatch/middleware/static.rb:113:in `call'
rack (1.6.1) lib/rack/sendfile.rb:113:in `call'
railties (4.2.1) lib/rails/engine.rb:518:in `call'
railties (4.2.1) lib/rails/application.rb:164:in `call'
rack (1.6.1) lib/rack/lock.rb:17:in `call'
rack (1.6.1) lib/rack/content_length.rb:15:in `call'
rack (1.6.1) lib/rack/handler/webrick.rb:89:in `service'
C:/Ruby193/lib/ruby/1.9.1/webrick/httpserver.rb:138:in `service'
C:/Ruby193/lib/ruby/1.9.1/webrick/httpserver.rb:94:in `run'
C:/Ruby193/lib/ruby/1.9.1/webrick/server.rb:191:in `block in start_thread'
Request

Parameters:

None
Toggle session dump
Toggle env dump
Response

Headers:

None
>>   

MODEL:

class Prevhead < ActiveRecord::Base  
  
  belongs_to :client
  belongs_to :carto
  belongs_to :costoli
  belongs_to :onda
  belongs_to :fusto
  belongs_to :inco
  belongs_to :confe
  belongs_to :resa
  belongs_to :costoli2
 
 filterrific(
  available_filters: [
    :with_client_id,
    :with_articolo
    ]
  )
  
  scope :with_client_id, lambda { |client_ids|
    where(client_id: [*client_ids])
  }
  scope :with_articolo, lambda { order('articolo ASC') }
  
  validates :client_id, :inclusion => {:in => 2..1000, :message => "Cliente non selezionato"}
  validates :articolo, presence: {message: "Articolo non definito"}
  validates :descrizione, presence: {message: "Descrizione non inserita"} 
    
  validates_numericality_of :qta, message: "Quantita non definita", on: :create
  validates_numericality_of :qta, message: "Quantita non definita", on: :edit
  
  validates_numericality_of :scarto, message: "Scarto non definito", on: :create
  validates_numericality_of :scarto, message: "Scarto non definito", on: :edit

  validates_numericality_of :dim1, message: "Altezza non definita", on: :create
  validates_numericality_of :dim1, message: "Altezza non definita", on: :edit

  validates_numericality_of :dim2, message: "Larghezza non definita", on: :create
  validates_numericality_of :dim2, message: "Larghezza non definita", on: :edit
                                             
  validates :carto_id, :inclusion => {:in => 2..1000, :message => "Cartoncino non selezionato"}
  validates :resa_id, :inclusion => {:in => 2..1000, :message => "Resa non selezionata"}
  validates :costoli_id, :inclusion => {:in => 2..1000, :message => "Linea non selezionata"}     
end

CONTROLLER:

class PrevheadsController < ApplicationController
  def index
    @filterrific = initialize_filterrific(
     Prevhead,
     params[:filterrific],
     select_options: {
      with_client_id: Client.options_for_select,
      },
      persistence_id: 'shared_key',
      default_filter_params: {},
      available_filters: [],
     ) or return
    @prevheads = @filterrific.find.paginate(:page => params[:page], :per_page => 12).order("num DESC","vers DESC").joins(:client)

    respond_to do |format|
      format.html
      format.js
    end
  end
  
  def show
    @prevhead = Prevhead.find(params[:id])
  end

  def new
    @prevhead = Prevhead.new
  end

  def edit
    @prevhead = Prevhead.joins(:client, :carto, :costoli, :fusto, :inco, :confe, :resa).find(params[:id])
  end

private
  def prevhead_params
    params.require(:prevhead).permit(:num, :vers, :client_id, :qta, :articolo, :descrizione, :qta, :scarto, :dim1, :dim2, :formatoc, :carto_id, :resa_id, :costoli_id, :costoli2_id, :onda_id, :fusto_id, :inco_id, :confe_id, :traspo, :data_elab, :co_carto, :co_stampa, :co_avvsta, :co_stampa2, :co_avvsta2, :co_onda, :co_fusto, :co_avvfust, :co_inco, :co_avvinco, :co_confe, :preventivo, :prevtraspo, :un_peso, :un_costo, :un_stampa, :un_stampa2, :un_coston, :un_costof, :un_costoi, :un_sovrap, :un_confe, :un_contenuto, :note, :desclinea2, :descform2, :descolor2, :descdiff2)
  end  
    
end

INDEX.HTML.ERB

<p id="notice"><%= notice %></p>

<%= form_for_filterrific @filterrific do |f| %>
  <div>
    Cliente
    <%= f.select(
      :with_client_id,
      @filterrific.select_options[:with_client_id]
    ) %>
  </div>  
  <div>
    Articolo
    <%# give the search field the 'filterrific-periodically-observed' class for live updates %>
    <%= f.text_field(
      :prod,
      class: 'filterrific-periodically-observed'
    ) %>
  </div>

  <div>
    <%= link_to(
      'Reset filters',
      reset_filterrific_url,
    ) %>
  </div>
  <%# add an automated spinner to your form when the list is refreshed %>
  <%= render_filterrific_spinner %>
<% end %>

<%= render(
  partial: 'zzz/elenco',
  locals: { prevheads: @prevheads}
) %>

<br>

PARTIAL zzz/_elenco

<p id="notice"><%= notice %></p>

<% @page_title="Preventivi" %>

<table>                                                              
	<tr>
      <td><div id="evtit">Numero</div></td>
      <td><div id="evtit">Versione</div></td>
      <td><div id="evtit">Cliente</div></td>
      <td><div id="evtit">Articolo</div></td>
      <td><div id="evtit">Descrizione</div></td>
      <td><div id="evtit">Quantità</div></td>
      <td align="right"><div id="evtit">Preventivo</div></td>
      <td align="right"><div id="evtit">Unitario</div></td>
      <td align="right"><div id="evtit">Trasporto</div></td>
      <td align="right"><div id="evtit">Unit Tot</div></td>
      <td align="center"><div id="evtit">Data</div></td>
      </tr>
    <% @prevheads.each do |prevhead| %>
      <tr>
      <td width="50" align="center"><%= prevhead.num %></td>
      <td width="50"><%= prevhead.vers %></td>
      <td width="100"><%= prevhead.client.ragsoc %></td>
      <td width="100"><%= prevhead.articolo %></td>
      <td width="200"><%= prevhead.descrizione %></td>
      <td width="50" align="right"><%= number_with_auto_precision(prevhead.qta, :separator => ',', :delimiter => '.')  %></td>
      <td width="90" align="right"><%= number_to_currency(prevhead.preventivo, :unit=>'€') %></td>
      <td width="50" align="right"><%= number_to_currency(prevhead.preventivo/prevhead.qta, :unit=>'€', :precision =>3) %></td>
      <td width="70" align="right"><%= number_to_currency(prevhead.traspo, :unit=>'€') %></td>
      <td width="60" align="right"><%= number_to_currency(prevhead.prevtraspo/prevhead.qta, :unit=>'€', :precision =>3) %></td>
      <td width="80" align="right"><%= prevhead.data_elab %></td>
     
        <td><%= button_to 'Mostra', prevhead_path(prevhead), method: :show %></td>
        <td><%= button_to 'Copia', copia_path(prevhead), method: :copia %></td>
        <td><%= link_to 'Stampa', stampa_path(prevhead), method: :stampa, target: :_blank %></td>

      </tr>
    <% end %>
</table>

<%= will_paginate @prevheads %>

<br>

TABLE prevheads

  create_table "prevheads", force: :cascade do |t|
    t.integer  "num",          limit: 4,                                          null: false
    t.integer  "vers",         limit: 4,                                          null: false
    t.integer  "client_id",    limit: 4,                                          null: false
    t.string   "articolo",     limit: 100,                                        null: false
    t.string   "descrizione",  limit: 200,                                        null: false
    t.decimal  "qta",                      precision: 10, scale: 2,               null: false
    t.decimal  "scarto",                   precision: 10, scale: 3,               null: false
    t.decimal  "dim1",                     precision: 10, scale: 3,               null: false
    t.decimal  "dim2",                     precision: 10, scale: 3,               null: false
    t.string   "formatoc",     limit: 100,                                        null: false
    t.integer  "carto_id",     limit: 4,                                          null: false
    t.integer  "resa_id",      limit: 4,                                          null: false
    t.integer  "costoli_id",   limit: 4,                                          null: false
    t.integer  "costoli2_id",  limit: 4,                                          null: false
    t.integer  "onda_id",      limit: 4,                            default: 1,   null: false
    t.integer  "fusto_id",     limit: 4,                            default: 1,   null: false
    t.integer  "inco_id",      limit: 4,                            default: 1,   null: false
    t.integer  "confe_id",     limit: 4,                            default: 1,   null: false
    t.decimal  "traspo",                   precision: 10, scale: 3, default: 0.0, null: false
    t.date     "data_elab"
    t.decimal  "co_carto",                 precision: 10, scale: 3, default: 0.0, null: false
    t.decimal  "co_stampa",                precision: 10, scale: 3, default: 0.0, null: false
    t.decimal  "co_avvsta",                precision: 10, scale: 3, default: 0.0, null: false
    t.decimal  "co_stampa2",               precision: 10, scale: 3, default: 0.0, null: false
    t.decimal  "co_avvsta2",               precision: 10, scale: 3, default: 0.0, null: false
    t.decimal  "co_onda",                  precision: 10, scale: 3, default: 0.0
    t.decimal  "co_fusto",                 precision: 10, scale: 3, default: 0.0
    t.decimal  "co_avvfust",               precision: 10, scale: 3, default: 0.0
    t.decimal  "co_inco",                  precision: 10, scale: 3, default: 0.0
    t.decimal  "co_avvinco",               precision: 10, scale: 3, default: 0.0
    t.decimal  "co_confe",                 precision: 10, scale: 3, default: 0.0
    t.decimal  "preventivo",               precision: 10, scale: 3, default: 0.0, null: false
    t.decimal  "prevtraspo",               precision: 10, scale: 3, default: 0.0, null: false
    t.decimal  "un_peso",                  precision: 10, scale: 3, default: 0.0, null: false
    t.decimal  "un_costo",                 precision: 10, scale: 3, default: 0.0, null: false
    t.decimal  "un_stampa",                precision: 10, scale: 3, default: 0.0, null: false
    t.decimal  "un_stampa2",               precision: 10, scale: 3, default: 0.0, null: false
    t.decimal  "un_coston",                precision: 10, scale: 3, default: 0.0
    t.decimal  "un_costof",                precision: 10, scale: 3, default: 0.0
    t.decimal  "un_costoi",                precision: 10, scale: 3, default: 0.0
    t.decimal  "un_sovrap",                precision: 10, scale: 3, default: 0.0
    t.decimal  "un_confe",                 precision: 10, scale: 3, default: 0.0
    t.decimal  "un_contenuto",             precision: 10, scale: 3, default: 0.0
    t.string   "note",         limit: 255
    t.string   "desclinea2",   limit: 50
    t.string   "descform2",    limit: 50
    t.string   "descolor2",    limit: 50
    t.string   "descdiff2",    limit: 50
    t.datetime "created_at",                                                      null: false
    t.datetime "updated_at",                                                      null: false
  end

Thank you for any suggestions ...

**Comment by alankessler** [comment]
You didn't define options_for_select on the client mode, but you used it
here:

params[:filterrific],
select_options: {
with_client_id: Client.options_for_select,
},
persistence_id: 'shared_key',

Follow the docs, check out the bottom of this page:

http://filterrific.clearcove.ca/pages/active_record_model_api.html

**Comment by gcalori** [comment]
Thank you,I missed this section.
Now the option select works fine.
I added the INDEX.JS.ERB  file:

<%# app/views/prevheads/index.js.erb %>
<% js = escape_javascript(
  render(partial: 'zzz/elenco', locals: { prevheads: @prevheads })
) %>
$("#filterrific_results").html("<%= js %>");

and a line in APPLICATION.JS:

// This is a manifest file that'll be compiled into application.js, which will include all the files
// listed below.
//
// Any JavaScript/Coffee file within this directory, lib/assets/javascripts, vendor/assets/javascripts,
// or any plugin's vendor/assets/javascripts directory can be referenced here using a relative path.
//
// It's not advisable to add code directly here, but if you do, it'll appear at the bottom of the
// compiled file.
//
// Read Sprockets README (https://github.com/rails/sprockets#sprockets-directives) for details
// about supported directives.
//
//= require jquery
//= require jquery_ujs
//= require turbolinks
//= require filterrific/filterrific-jquery
//= require_tree .

but nothing changes when I select an option from the combo box .....

**Comment by gcalori** [comment]
sorry I misunderstood the button...

**Comment by alankessler** [comment]
Gcalori,

Why don't you ask these questions on stackoverflow? This page is for reporting bugs in the gem. These aren't bugs; you're just asking for basic programming support.

**Comment by gcalori** [comment]
sorry,
I thought it was a support forum.
thank you.
