### ISSUE TITLE
"Filter by (non) existence of has_many association" has wrong condition

### ISSUE THREAD

**Issue by contradictioned** [jhund/filterrific#64]
At least under Rails 4.2.0 it is wrong. In the documentation under http://filterrific.clearcove.ca/pages/active_record_scope_patterns.html#filter_by_existence_has_many you say to use 

    scope :with_comments, lambda {
      where(
        'EXISTS (SELECT 1 FROM students, comments WHERE students.id = comments.student_id)'
      )
    }

which "finds all students who have posted at least one comment."

This is not true, the code is translated into

    SELECT "students".* FROM "students" WHERE ( EXISTS (SELECT 1 from students, comments WHERE students.id = comments.student_id)

So the WHERE-predicate is independent from the row of the outer "students" column and this way you get either the whole students table, if there is at least one student with a comment, or else an empty result set.

A fix for this would be to use

    scope :with_comments, lambda {
      where(
        'EXISTS (SELECT 1 FROM  comments WHERE students.id = comments.student_id)'
      )
    }

(so without the additional "FROM students" in the inner query) which translates to 

    SELECT "students".* FROM "students" WHERE ( EXISTS (SELECT 1 from comments WHERE students.id = comments.student_id)

Analogous for the "non existence" part.

**Comment by jhund** [comment]
@contradictioned thank you very much for the correction. I updated the documentation accordingly.
