### ISSUE TITLE
undefined method `initialize_filterrific'

### ISSUE THREAD

**Issue by echan00** [jhund/filterrific#75]
I have been getting this error since upgrading to the new version of filterrific.

I believe its because filterrific is an action_controller_extension and I am using it in my model class to do something with the filtered list with the filtered params.

Any thoughts about what to do here?

**Comment by jhund** [comment]
You suspicion sounds right. `initialize_filterrific` is indeed controller specific and not available in the model.

`initialize_filterrific` is just a convenience wrapper around manually initializing Filterrific. It also does things like extracting and sanitizing params and handling session persistence. All you need from that method is the line that [initializes the Filterrific::ParamSet](https://github.com/jhund/filterrific/blob/f93f21a7d4deb2ec8150a0c096eb8895b9decbc2/lib/filterrific/action_controller_extension.rb#L48):

`filterrific = Filterrific::ParamSet.new(model_class, f_params)`

Where `model_class` is your ActiveRecord class or a Relation and `f_params` is a hash of filterrific params.

**Comment by echan00** [comment]
Cool, I ended up moving the function to a controller...  I presume this thread would be a good to have lying around for the next person who ran into this problem as well.
