### ISSUE TITLE
It is needed example with checkboxes

### ISSUE THREAD

**Issue by sandiktopas** [jhund/filterrific#9]
Could someone give example with checkboxes?

**Comment by steakchaser** [comment]
For Rails 4 how about using the `collection_check_boxes` helper:

```ruby
f.collection_check_boxes :with_author_ids, Author.all.map{|a| a.name, a.id}, :last, :first
```

**Comment by steakchaser** [comment]
You can also do it this way with the `check_box` form helper:

```ruby
<% Author.all.each do |a| %>
  <%= f.check_box(:with_author_ids, {multiple: true}, a.id, false %>
  <%= a.name %>
<% end %>
```

NOTE: I think you want to stick with using the form builder object `f`, without this filterrific cannot set defaults or remember choices via the session.

**Comment by wtoalabi** [comment]
My need is slightly different. How do I make checkbox work with predefined values. For instance, I have a "hobby"  field with values like Reading, Travelling, Dancing... I want users to select and filter as many hobbies as possible. How do I present this on  the index view?  Thanks!
