### ISSUE TITLE
Problematic piece of code in the documentation

### ISSUE THREAD

**Issue by acrolink** [jhund/filterrific#90]
Thanks for this great utility. Inside Index definition in the documentation wrote these lines:

```
      persistence_id: 'shared_key',
      default_filter_params: {},
      available_filters: [],
```

I have noticed that these three lines make the filter non-functional (filters nothing). If I omit them, everything works perfectly. Any idea what might be going on here? Thanks.

**Comment by blaedj** [comment]
The `available_filters` parameter specifies which filters are allowed, and will override the filters defined on the model. The code in the documentation sets the applied filters to none, regardless what you define on the model.

**Comment by acrolink** [comment]
Thank @blaedj for the clarification.
